#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

mkdir -p $tmp/bin
cp $ARCHIVE/grpc_health_probe-linux-amd64 $tmp/bin/grpc_health_probe
chmod a+x $tmp/bin/grpc_health_probe

test -n "$MERIDIODIR" || MERIDIODIR=$(readlink -f $dir/../../../../../../../..)
test -d $MERIDIODIR/cmd/load-balancer || die "Meridio src not found"
cd $MERIDIODIR
go build -o $tmp/bin/proxy -ldflags "-X main.version=$meridio_version" ./cmd/proxy 1>&2 || die "go build"
strip $tmp/bin/proxy
cd $dir

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
