apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: $(SERVICE_NAMESPACE)
    control-plane: meridio-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    control-plane: meridio-operator
spec:
  selector:
    matchLabels:
      control-plane: meridio-operator
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: meridio-operator
    spec:
      securityContext:
        runAsNonRoot: true
      volumes:
      - name: templates-volume
        configMap:
          name: deployment-templates
      containers:
      - image: operator:latest
        imagePullPolicy: IfNotPresent
        name: operator
        env:
          - name: RESOURCE_NAME_PREFIX
            value: ""
          - name: NSM_REGISTRY_SERVICE
            value: "nsm-registry-svc.nsm:5002"
          - name: LOG_LEVEL
            value: "DEBUG"
          - name: NSP_SERVICE_ACCOUNT
            value: "meridio-nsp"
          - name: FE_SERVICE_ACCOUNT
            value: "meridio-fes"
          - name: IMAGE_PULL_SECRET
            value: "" # multiple secrets supported, use "," as the delimiter
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GRPC_PROBE_RPC_TIMEOUT
            value: "1s"
          - name: CONDUIT_MTU
            value: "1500"
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          periodSeconds: 20
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          periodSeconds: 10
          timeoutSeconds: 2
        startupProbe:
          httpGet:
            path: /readyz
            port: 8081
          failureThreshold: 100
          periodSeconds: 3
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 300m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /home/meridio/deployment
          name: templates-volume
      serviceAccountName: operator
      terminationGracePeriodSeconds: 10
