{
 "title": "Meridio",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Target Hits",
   "type": "table",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "meridio_conduit_stream_target_hit_packets_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "meridio_conduit_stream_target_hit_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow List",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "meridio_conduit_stream_flow_matches_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow Match (packet per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(flow, stream, conduit, trench) (rate(meridio_conduit_stream_flow_matches_total[$__rate_interval]))",
     "legendFormat": "{{flow}}.{{stream}}.{{conduit}}.{{trench}}"
    }
   ]
  },
  {
   "title": "Stream (packets per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(trench, conduit, stream) (rate(meridio_conduit_stream_target_hit_packets_total[$__rate_interval]))",
     "legendFormat": "{{stream}}.{{conduit}}.{{trench}}"
    }
   ]
  },
  {
   "title": "Stream (bytes per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by(trench, conduit, stream) (rate(meridio_conduit_stream_target_hit_bytes_total[$__rate_interval]))",
     "legendFormat": "{{stream}}.{{conduit}}.{{trench}}"
    }
   ]
  },
  {
   "title": "Interface Metrics",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "meridio_interface_rx_bytes_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "meridio_interface_tx_bytes_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "meridio_interface_rx_packets_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "meridio_interface_tx_packets_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "meridio_interface_rx_errors_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "meridio_interface_tx_errors_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "meridio_interface_rx_dropped_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "meridio_interface_tx_dropped_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by(trench, conduit, attractor) (rate(meridio_interface_rx_bytes_total[$__rate_interval]))",
     "legendFormat": "rx_bytes.{{conduit}}{{attractor}}.{{trench}}"
    },
    {
     "expr": "sum by(trench, conduit, attractor) (rate(meridio_interface_tx_bytes_total[$__rate_interval]))",
     "legendFormat": "tx_bytes.{{conduit}}{{attractor}}.{{trench}}"
    },
    {
     "expr": "sum by(trench, conduit, attractor) (rate(meridio_interface_rx_packets_total[$__rate_interval]))",
     "legendFormat": "rx_packets.{{conduit}}{{attractor}}.{{trench}}"
    },
    {
     "expr": "sum by(trench, conduit, attractor) (rate(meridio_interface_tx_packets_total[$__rate_interval]))",
     "legendFormat": "tx_packets.{{conduit}}{{attractor}}.{{trench}}"
    },
    {
     "expr": "sum by(trench, conduit, attractor) (rate(meridio_interface_rx_errors_total[$__rate_interval]))",
     "legendFormat": "rx_errors.{{conduit}}{{attractor}}.{{trench}}"
    },
    {
     "expr": "sum by(trench, conduit, attractor) (rate(meridio_interface_tx_errors_total[$__rate_interval]))",
     "legendFormat": "tx_errors.{{conduit}}{{attractor}}.{{trench}}"
    },
    {
     "expr": "sum by(trench, conduit, attractor) (rate(meridio_interface_rx_dropped_total[$__rate_interval]))",
     "legendFormat": "rx_dropped.{{conduit}}{{attractor}}.{{trench}}"
    },
    {
     "expr": "sum by(trench, conduit, attractor) (rate(meridio_interface_tx_dropped_total[$__rate_interval]))",
     "legendFormat": "tx_dropped.{{conduit}}{{attractor}}.{{trench}}"
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "meridio_attractor_gateway_exported_routes",
     "legendFormat": "__auto"
    },
    {
     "expr": "meridio_attractor_gateway_imported_routes",
     "legendFormat": "__auto"
    },
    {
     "expr": "meridio_attractor_gateway_preferred_routes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}