#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

mkdir -p $tmp/bin
cp $ARCHIVE/grpc_health_probe-linux-amd64 $tmp/bin/grpc_health_probe
chmod a+x $tmp/bin/grpc_health_probe

test -n "$MERIDIODIR" || MERIDIODIR=$(readlink -f $dir/../../../../../../../..)
test -d $MERIDIODIR/cmd/load-balancer || die "Meridio src not found"
cd $MERIDIODIR
log "main.version=$meridio_version"
go build -o $tmp/bin/load-balancer -ldflags "-X main.version=$meridio_version" ./cmd/load-balancer 1>&2 || die "go build"
strip $tmp/bin/load-balancer
cd $dir

nfqlb=/tmp/$USER/nfqlb/nfqlb/nfqlb
if test -x $nfqlb; then
	log "Local built nfqlb"
	mkdir -p $tmp/bin
	cp $nfqlb $tmp/bin
else
	nfqlb=nfqlb-0.8.0
	log "Using $nfqlb"
	ar=$ARCHIVE/Downloads/$nfqlb.tar.xz
	test -r $ar || ar=$HOME/Downloads/$nfqlb.tar.xz
	test -r $ar || die "Not readable [$ar]"
	tar -C $tmp --strip-components=1 -xf $ar $nfqlb/bin
fi

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
