apiVersion: v1
kind: Service
metadata:
  name: meridio-tunnel
spec:
  selector:
    app: meridio-tg
  externalTrafficPolicy: Local
  ports:
  - port: 5533
    name: vxlan
    protocol: UDP
  type: LoadBalancer
