---

registry: registry.nordix.org
organization: cloud-native/meridio
tag: latest
pullPolicy: IfNotPresent

maxTokenLifetime: 10m
fsGroup: 3000

nsm:
  namespace: nsm
  registryService: nsm-registry-svc
  registryPort: 5002

trench:
  name: trench-a

attractor:
  name: attractor-a

configuration:
  configmap: meridio-configuration

init:
  image: init
  version: latest

loadBalancer:
  image: stateless-lb
  version: latest
  networkServiceName: load-balancer
  probe:
    readiness:
      service: "Readiness"

frontEnd:
  image: frontend
  version: latest
  probe:
    readiness:
      service: "Readiness"

proxy:
  image: proxy
  version: latest
  networkServiceName: proxy.load-balancer
  probe:
    readiness:
      service: "Readiness"

ipam:
  image: ipam
  version: latest
  port: 7777
  targetPort: 7777
  serviceName: ipam-service
  probe:
    readiness:
      service: "Readiness"

nsp:
  image: nsp
  version: latest
  port: 7778
  targetPort: 7778
  serviceName: nsp-service
  probe:
    readiness:
      service: ""
      addr: :7778
      spiffe: true

ipFamily: ipv4  # ipv4 / ipv6 / dualstack

vips:
  - name: vip1
    address: 20.0.0.1/32
  - name: vip2
    address: 2000::1/128
  - name: vip3
    address: 40.0.0.0/24

subnetPool:
  ipv4: 172.16.0.0/16
  ipv6: fd00::/48
  conduitPrefixLength:
    ipv4: 20
    ipv6: 56
  nodePrefixLength:
    ipv4: 24
    ipv6: 64

tunnel:
  peer: 192.168.1.202
  dev: tunnel0
  id: 100
  ipv4: 169.254.100.1/24
  ipv6: fd00:100::169.254.100.1/120
  fe:
    gateways:
      - name: gateway1
        address: 169.254.100.254
        ipFamily: ipv4
        bfd: false
        protocol: static
      - name: gateway2
        address: fd00:100::169.254.100.254
        ipFamily: ipv6
        bfd: false
        protocol: static

probe:
  addr: unix:///tmp/health.sock
  service: ""
