# This Role grants permissions to interact with Lease objects.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ipam-leader-election-role
rules:
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - "leases"
  verbs:
  - "get"
  - "create"
  - "update"
  - "patch"
