---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "meridio.ipam.serviceName" . }}
spec:
  selector:
    app: ipam-{{ .Values.trench.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.ipam.port }}
      targetPort: {{ .Values.ipam.targetPort }}