---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "meridio.nsp.serviceName" . }}
spec:
  selector:
    app: nsp-{{ .Values.trench.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.nsp.port }}
      targetPort: {{ .Values.nsp.targetPort }}