---
apiVersion: v1
kind: Service
metadata:
  name: nsm-registry-svc
spec:
  selector:
    app: registry
  ports:
    - name: nsm-registry-svc
      protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer