---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: registry-k8s-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["networkservicemesh.io"]
    resources:
      - "networkservices"
      - "networkserviceendpoints"
    verbs: ["*"]