// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/ambassador/tap/trench/factory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/nordix/meridio/api/ambassador/v1"
	types "github.com/nordix/meridio/pkg/ambassador/tap/types"
)

// MockConduitFactory is a mock of ConduitFactory interface.
type MockConduitFactory struct {
	ctrl     *gomock.Controller
	recorder *MockConduitFactoryMockRecorder
}

// MockConduitFactoryMockRecorder is the mock recorder for MockConduitFactory.
type MockConduitFactoryMockRecorder struct {
	mock *MockConduitFactory
}

// NewMockConduitFactory creates a new mock instance.
func NewMockConduitFactory(ctrl *gomock.Controller) *MockConduitFactory {
	mock := &MockConduitFactory{ctrl: ctrl}
	mock.recorder = &MockConduitFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConduitFactory) EXPECT() *MockConduitFactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockConduitFactory) New(arg0 *v1.Conduit) (types.Conduit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", arg0)
	ret0, _ := ret[0].(types.Conduit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockConduitFactoryMockRecorder) New(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockConduitFactory)(nil).New), arg0)
}
