apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: operator
        volumeMounts:
        - name: resource-templates
          mountPath: "/home/meridio/template/resource"
          readOnly: true
      volumes:
      - name: resource-templates
        configMap:
          name: resource-templates

