---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: forwarder-vlan
  labels:
    app: forwarder-vlan
spec:
  selector:
    matchLabels:
      app: forwarder-vlan
  template:
    metadata:
      labels:
        spiffe.io/spiffe-id: "true"
        app: forwarder-vlan
    spec:
      hostNetwork: true
      containers:
        - name: forwarder-vlan
          image: registry.nordix.org/cloud-native/nsm/forwarder-vlan:latest
          imagePullPolicy: {{ .Values.pullPolicy }}
          securityContext:
            privileged: true
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_CONNECT_TO
              value: "unix:///var/lib/networkservicemesh/nsm.io.sock"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NSM_LABELS
              value: forwarder:forwarder-vlan
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate