apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipam
  labels:
    app: ipam
spec:
  replicas: 1
  serviceName: ipam
  selector:
    matchLabels:
      app: ipam
  template:
    metadata:
      labels:
        app: ipam
    spec:
      containers:
        - name: ipam
          image: # to be filled by operator
          imagePullPolicy: # Kubernetes default according to image tag
          readinessProbe: # will be overwritten by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:8000
                - -connect-timeout=100ms
                - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
          livenessProbe: # will be overwritten by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:8000
                - -connect-timeout=100ms
                - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: IPAM_PORT
              value: "7777"
            - name: IPAM_DATASOURCE
              value: /run/ipam/data/registry.db
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: ipam-data
              mountPath: /run/ipam/data
              readOnly: false
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
  volumeClaimTemplates:
    - metadata:
        name: ipam-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
