# Source: meridio/templates/proxy.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: # to be filled by operator
      initContainers:
        - name: sysctl-init
          image: # to be filled by operator
          imagePullPolicy: # Kubernetes default according to image tag
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args: # to be filled by operator according to the Trench
      containers:
        - name: proxy
          image: # to be filled by operator if not specified
          imagePullPolicy: # Kubernetes default according to image tag
          readinessProbe: # will be overwritten by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:8000
                - -connect-timeout=100ms
                - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
          livenessProbe: # will be overwritten by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:8000
                - -connect-timeout=100ms
                - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NSM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NSM_CONFIG_MAP_NAME
              value: # to be filled by operator
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSM_SERVICE_NAME
              value: # to be filled by operator
            - name: NSM_SUBNET_POOLS
              value: # to be filled by operator
            - name: NSM_SUBNET_PREFIX_LENGTHS
              value: # to be filled by operator
            - name: NSM_IPAM_SERVICE
              value: # to be filled by operator
            - name: NSM_NETWORK_SERVICE_NAME
              value: # to be filled by operator
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
