---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spire

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: spire-server
  namespace: spire
  files:
  - server.conf
- name: spire-agent
  namespace: spire
  files:
  - agent.conf
- name: k8s-workload-registrar
  namespace: spire
  files:
    - k8s-workload-registrar.conf

resources:
- k8s-workload-registrar-crd.yaml
- spire-namespace.yaml
- agent-account.yaml
- agent-cluster-role.yaml
- agent-daemonset.yaml
- server-account.yaml
- server-cluster-role.yaml
- server-service.yaml
- server-statefulset.yaml
- spire-bundle-configmap.yaml
- k8s-workload-registrar-cluster-role.yaml
- k8s-workload-registrar-service.yaml
- k8s-workload-registrar-validating-webhook-configuration.yaml
