---

# https://github.com/spiffe/spire/blob/main/support/k8s/k8s-workload-registrar/mode-crd/README.md#quick-start

clusterName: "meridio"
trustDomain: "meridio.nordix.org"

registry: gcr.io
org: spiffe-io
version: 1.1.0