#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}
findfile() {
	f=$ARCHIVE/$1
	test -r $f && return 0
	f=$HOME/Downloads/$1
	test -r $f || die "File not found [$f]"
}


test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

$XCLUSTER install_prog --dest=$tmp envsubst

if test "$__use_multus" = "yes"; then
	ovl_multus=$($XCLUSTER ovld multus)
	SETUP=None $ovl_multus/tar - | tar -C $tmp -x
fi

if test "$nsm_local" = "yes"; then
	nsmsh=$($XCLUSTER ovld nsm-ovs)/nsm-ovs.sh
	test -x $nsmsh || die "Not executable [$nsmsh]"
	$nsmsh set_local_image \
		$tmp/etc/kubernetes/forwarder-test-local/load-balancer-template.yaml \
		$tmp/etc/kubernetes/forwarder-test/nsc-template.yaml \
		$tmp/etc/kubernetes/forwarder-test/load-balancer-template.yaml \
		$tmp/etc/kubernetes/forwarder-test/nse-template.yaml
fi

findfile ctraffic.gz
zcat $f > $tmp/bin/ctraffic
chmod a+x $tmp/bin/ctraffic

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
