apiVersion: apps/v1
kind: Deployment
metadata:
  name: meridio-load-balancer
  labels:
    app: meridio-load-balancer
spec:
  selector:
    matchLabels:
      app: meridio-load-balancer
  replicas: 2
  template:
    metadata:
      labels:
        app: meridio-load-balancer
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
         { "name" : "meridio-$NAME",
           "namespace": "default",
           "interface": "nsm-1" }
        ]'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "meridio-load-balancer"
            topologyKey: kubernetes.io/hostname
      initContainers:
        - name: sysctl-init
          image: registry.nordix.org/cloud-native/meridio/busybox:1.29
          securityContext:
            privileged: true
          volumeMounts:
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
          command: ["/bin/sh"]
          args:
            - -c
            - sysctl -w net.ipv4.conf.all.forwarding=1; sysctl -w net.ipv6.conf.all.forwarding=1; sysctl -w net.ipv4.fib_multipath_hash_policy=1
      containers:
        - name: load-balancer
          image: registry.nordix.org/cloud-native/meridio/load-balancer:local
          imagePullPolicy: IfNotPresent
          startupProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=unix:///tmp/health.sock
              - -service=
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            initialDelaySeconds: 0
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 30
          readinessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=unix:///tmp/health.sock
              - -service=Readiness
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=unix:///tmp/health.sock
              - -service=
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_SERVICE_NAME
              value: $CONDUIT1.$NAME.$NS
            - name: NSM_CONDUIT_NAME
              value: $CONDUIT1
            - name: NSM_TRENCH_NAME
              value: $NAME
            - name: NSM_NSP_SERVICE
              value: meridio-nsp-$NAME:7778
            - name: NSM_LOG_LEVEL
              value: "DEBUG"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
        - name: fe
          image: registry.nordix.org/cloud-native/meridio/frontend:local
          imagePullPolicy: IfNotPresent
          startupProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=unix:///tmp/health.sock
              - -service=
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            initialDelaySeconds: 0
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 30
          livenessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=unix:///tmp/health.sock
              - -service=
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=unix:///tmp/health.sock
              - -service=Readiness
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NFE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NFE_LOG_BIRD
              value: "true"
            - name: NFE_ECMP
              value: "true"
            - name: NFE_EXTERNAL_INTERFACE
              value: "nsm-1"
            - name: NFE_NSP_SERVICE
              value: meridio-nsp-$NAME:7778
            - name: NFE_CONFIG_MAP_NAME
              value: meridio-configuration-$NAME
            - name: NFE_TRENCH_NAME
              value: $NAME
            - name: NFE_ATTRACTOR_NAME
              value: "attractor1"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
