apiVersion: apps/v1
kind: Deployment
metadata:
  name: meridio-nse
  labels:
    app: meridio-nse
spec:
  selector:
    matchLabels:
      app: meridio-nse
  template:
    metadata:
      labels:
        app: meridio-nse
    spec:
      containers:
        - name: nse
          image: ghcr.io/networkservicemesh/cmd-nse-remote-vlan:v1.3.0-rc.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_CONNECT_TO
              value: nsm-registry.default:5002
            - name: NSM_SERVICES
              value: "$NSM_SERVICES"
            - name: NSM_CIDR_PREFIX
              value: "$NSM_CIDR_PREFIX"
            - name: NSM_IPV6_PREFIX
              value: "$NSM_IPV6_PREFIX"
            - name: NSM_POINT2POINT
              value: "True"
            - name: NSM_REGISTER_SERVICE
              value: "True"
            - name: NSM_LISTEN_ON
              value: tcp://:5003
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
