---
# Source: target/templates/target.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meridio-app
  labels:
    app: meridio-app
spec:
  selector:
    matchLabels:
      app: meridio-app
  replicas: 4
  template:
    metadata:
      labels:
        app: meridio-app
    spec:
      containers:
        - name: meridio-app
          image: registry.nordix.org/cloud-native/meridio/meridio-app:local
          imagePullPolicy: IfNotPresent
          env:
            - name: TRENCH
              value: $NAME
            - name: NSM_SERVICE
              value: $CONDUIT1
            - name: STREAM
              value: $STREAM1
            - name: MERIDIO_AMBASSADOR_SOCKET
              value: unix:///var/lib/meridio/ambassador.sock
            - name: NO_START
              value: "no"
          ports:
          - containerPort: 5001
          - containerPort: 5003
          securityContext:
            privileged: true
          volumeMounts:
            - name: meridio-socket
              mountPath: /var/lib/meridio
              readOnly: false
        - name: tapa
          image: registry.nordix.org/cloud-native/meridio/tapa:local
          imagePullPolicy: IfNotPresent
          startupProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=unix:///tmp/health.sock
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 2
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=unix:///var/lib/meridio/ambassador.sock
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            initialDelaySeconds: 0
          livenessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=unix:///tmp/health.sock
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            failureThreshold: 3
            initialDelaySeconds: 3
            timeoutSeconds: 3
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: MERIDIO_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MERIDIO_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MERIDIO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MERIDIO_NSM_SOCKET
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: MERIDIO_NSP_SERVICE_NAME
              value: meridio-nsp
            - name: MERIDIO_NSP_SERVICE_PORT
              value: "7778"
            - name: MERIDIO_SOCKET
              value: "/var/lib/meridio/ambassador.sock"
            - name: MERIDIO_MAX_TOKEN_LIFETIME
              value: 10m
            - name: MERIDIO_NSP_ENTRY_TIMEOUT
              value: 2m
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
            - name: meridio-socket
              mountPath: /var/lib/meridio
              readOnly: false
          securityContext:
            privileged: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
        - name: meridio-socket
          emptyDir: {}
